package vn.sonnl.gigaman.helpers;

import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.math.Vector2;

public class Constants {
    public static final String GAME_NAME = "Giga Man";
    public static final Color BACKGROUND_COLOR = Color.TEAL;
    public static final int APP_WIDTH = 800;
    public static final int APP_HEIGHT = 480;
    public static final float WORLD_TO_SCREEN = 32;

    public static final Vector2 WORLD_GRAVITY = new Vector2(0, -10);
    public static final float GROUND_X = 0;
    public static final float GROUND_Y = 0;
    public static final float GROUND_WIDTH = 25f;
    public static final float GROUND_HEIGHT = 2f;
    public static final float GROUND_DENSITY = 0f;
    public static final float RUNNER_X = 2;
    public static final float RUNNER_Y = GROUND_Y + GROUND_HEIGHT;
    public static final float RUNNER_WIDTH = 1f;
    public static final float RUNNER_HEIGHT = 2f;
    public static final float RUNNER_GRAVITY_SCALE = 3f;
    public static final float RUNNER_DENSITY = 0.5f;
    public static final float GIGAMAN_SHOOT_X = 2f;
    public static final float GIGAMAN_SHOOT_Y = 1.5f;
    public static final Vector2 RUNNER_JUMPING_LINEAR_IMPULSE = new Vector2(0, 13f);
    public static final float RUNNER_HIT_ANGULAR_IMPULSE = 10f;

    public static final float ENEMY_X = 25f;
    public static final float ENEMY_DENSITY = RUNNER_DENSITY;
    public static final float RUNNING_SHORT_ENEMY_Y = 1.5f;
    public static final float RUNNING_LONG_ENEMY_Y = 2f;
    public static final float FLYING_ENEMY_Y = 3f;
    public static final Vector2 ENEMY_LINEAR_VELOCITY = new Vector2(-10f, 0);

    public static final String BACKGROUND_ASSETS_ID = "background";
    public static final String GROUND_ASSETS_ID = "ground";
    public static final String GIGAMAN_RUNNING_ASSETS_ID = "runner_running";
    public static final String RUNNER_DODGING_ASSETS_ID = "runner_dodging";
    public static final String GIGAMAN_HIT_ASSETS_ID = "gigaman_hit";
    public static final String GIGAMAN_JUMPING_ASSETS_ID = "gigaman_jumping";
    public static final String RUNNING_SMALL_ENEMY_ASSETS_ID = "running_small_enemy";
    public static final String RUNNING_LONG_ENEMY_ASSETS_ID = "running_long_enemy";
    public static final String RUNNING_BIG_ENEMY_ASSETS_ID = "running_big_enemy";
    public static final String RUNNING_WIDE_ENEMY_ASSETS_ID = "running_wide_enemy";
    public static final String FLYING_SMALL_ENEMY_ASSETS_ID = "flying_small_enemy";
    public static final String FLYING_WIDE_ENEMY_ASSETS_ID = "flying_wide_enemy";
    public static final String BULLET_ASSETS_ID = "bullet";

    public static final String BACKGROUND_IMAGE_PATH = "background.png";
    public static final String GROUND_IMAGE_PATH = "ground.png";
    public static final String SPRITES_ATLAS_PATH = "sprites.txt";
    public static final String GIGAMAN_ATLAS_PATH = "gigaman.pack.atlas";
    public static final String[] GIGAMAN_RUNNING_REGION_NAMES = new String[] {"walk-right-1", "walk-right-2","walk-right-3"};
    public static final String RUNNER_DODGING_REGION_NAME = "walk-right-2";
    public static final String GIGAMAN_HIT_REGION_NAME = "standing-right";
    public static final String GIGAMAN_JUMPING_REGION_NAME = "jumping-right";
    public static final String BULLET_REGION_NAME = "bullet";

    public static final String[] RUNNING_SMALL_ENEMY_REGION_NAMES = new String[] {"ladyBug_walk1", "ladyBug_walk2"};
    public static final String[] RUNNING_LONG_ENEMY_REGION_NAMES = new String[] {"barnacle_bite1", "barnacle_bite2"};
    public static final String[] RUNNING_BIG_ENEMY_REGION_NAMES = new String[] {"spider_walk1", "spider_walk2"};
    public static final String[] RUNNING_WIDE_ENEMY_REGION_NAMES = new String[] {"worm_walk1", "worm_walk2"};
    public static final String[] FLYING_SMALL_ENEMY_REGION_NAMES = new String[] {"bee_fly1", "bee_fly2"};
    public static final String[] FLYING_WIDE_ENEMY_REGION_NAMES = new String[] {"fly_fly1", "fly_fly2"};

    public static final String SOUND_ON_REGION_NAME = "sound_on";
    public static final String SOUND_OFF_REGION_NAME = "sound_off";
    public static final String MUSIC_ON_REGION_NAME = "music_on";
    public static final String MUSIC_OFF_REGION_NAME = "music_off";
    public static final String PAUSE_REGION_NAME = "pause";
    public static final String PLAY_REGION_NAME = "play";
    public static final String BIG_PLAY_REGION_NAME = "play_big";
    public static final String LEADERBOARD_REGION_NAME = "leaderboard";
    public static final String ABOUT_REGION_NAME = "about";
    public static final String CLOSE_REGION_NAME = "close";
    public static final String SHARE_REGION_NAME = "share";
    public static final String ACHIEVEMENTS_REGION_NAME = "star";

    public static final String TUTORIAL_LEFT_REGION_NAME = "tutorial_left";
    public static final String TUTORIAL_RIGHT_REGION_NAME = "tutorial_right";
    public static final String TUTORIAL_LEFT_TEXT = "\nTap left to dodge";
    public static final String TUTORIAL_RIGHT_TEXT = "\nTap right to jump";

    public static final String RUNNER_JUMPING_SOUND = "jump.wav";
    public static final String RUNNER_HIT_SOUND = "hit.wav";
    public static final String GAME_MUSIC = "fun_in_a_bottle.mp3";

    public static final String FONT_NAME = "roboto_bold.ttf";

    public static final String ABOUT_TEXT = "Developed by: Son Nghiem\nPowered by: " +
            "@libgdx\nGraphics: @kenneywings\nMusic: @kmacleod";
    public static final String SHARE_MESSAGE_PREFIX = "Check out " + GAME_NAME + " %s";
    public static final String SHARE_TITLE = "Share!";
    public static final String PAUSED_LABEL = "Paused";

    public static final float WORLD_SIZE = 480;
    public static final float KILL_PLANE = -100;
    public static final String TEXTURE_ATLAS = "images/gigaman.pack.atlas";
    public static final float FOLLOW_CAM_MOVE_SPEED = 180;
    public static final String STANDING_RIGHT = "standing-right";
    public static final String STANDING_LEFT = "standing-left";
    public static final String JUMPING_RIGHT = "jumping-right";
    public static final String JUMPING_LEFT = "jumping-left";
    public static final String WALKING_RIGHT_2 = "walk-right-2";
    public static final String WALKING_LEFT_2 = "walk-left-2";
    public static final String WALKING_RIGHT_1 = "walk-right-1";
    public static final String WALKING_LEFT_1 = "walk-left-1";
    public static final String WALKING_RIGHT_3 = "walk-right-3";
    public static final String WALKING_LEFT_3 = "walk-left-3";
    public static final float WALK_LOOP_DURATION = 0.25f;
    public static final Vector2 GIGAMAN_EYE_POSITION = new Vector2(16,24);
    public static final float GIGAMAN_EYE_HEIGHT = 16;
    public static final String PLATFORM = "platform";
    public static final int PLATFORM_EDGE = 8;
    public static final float GIGAMAN_MOVE_SPEED = 64;
    public static final float JUMP_SPEED = 200;
    public static final float MAX_JUMP_DURATION = 0.1f;
    public static final float GRAVITY = 400;
    public static final float GIGAMAN_STANCE_WIDTH = 21;
    public static final String ENEMY = "enemy";
    public static final Vector2 ENEMY_CENTER = new Vector2(14, 22);
    public static final float ENEMY_MOVEMENT_SPEED = 30;
    public static final float ENEMY_BOUNCE_AMPLITUDE = 4;
    public static final float ENEMY_BOUNCE_PERIOD = 2;

    public static final float GIGAMAN_HEIGHT = 23;
    public static final Vector2 REBOUND_VELOCITY = new Vector2(200, 200);
    public static final float ENEMY_COLLISION_RADIUS = 15;
    public static final String BULLET = "bullet";
    public static final Vector2 BULLET_CENTER = new Vector2(3,2);
    public static final float BULLET_MOVE_SPEED = 150;
    public static final String BURST_LARGE = "explosion-large";
    public static final String BURST_MEDIUM = "explosion-medium";
    public static final String BURST_SMALL = "explosion-small";
    public static final Vector2 BURST_CENTER = new Vector2(8, 8);
    public static final float BURST_DURATION = 0.5f;
    public static final String POWERUP = "powerup";
    public static final Vector2 POWERUP_CENTER = new Vector2(7, 5);
    public static final Vector2 CANNON_OFFSET = new Vector2(12, -7);
    public static final int ENEMY_HEALTH = 5;
    public static final float ENEMY_SHOT_RADIUS = 17;
    public static final int INITIAL_BULLET = 10;
    public static final int POWERUP_BULLET = 10;
    public static final String LEVEL_DIR = "levels";
    public static final String LEVEL_FILE_EXTENSION = "dt";
    public static final String LEVEL_COMPOSITE = "composite";
    public static final String LEVEL_9PATCHES = "sImage9patchs";
    public static final String LEVEL_IMAGES = "sImages";
    public static final String LEVEL_ERROR_MESSAGE = "There was a problem loading the level.";
    public static final String LEVEL_IMAGENAME_KEY = "imageName";
    public static final String LEVEL_X_KEY = "x";
    public static final String LEVEL_Y_KEY = "y";
    public static final String LEVEL_WIDTH_KEY = "width";
    public static final String LEVEL_HEIGHT_KEY = "height";
    public static final String LEVEL_IDENTIFIER_KEY = "itemIdentifier";
    public static final String LEVEL_ENEMY_TAG = "Enemy";
    public static final Vector2 EXIT_PORTAL_CENTER = new Vector2(31,31);
    public static final String EXIT_PORTAL_SPRITE_1 = "exit-portal-1";
    public static final String EXIT_PORTAL_SPRITE_2 = "exit-portal-2";
    public static final String EXIT_PORTAL_SPRITE_3 = "exit-portal-3";
    public static final String EXIT_PORTAL_SPRITE_4 = "exit-portal-4";
    public static final String EXIT_PORTAL_SPRITE_5 = "exit-portal-5";
    public static final String EXIT_PORTAL_SPRITE_6 = "exit-portal-6";
    public static final float EXIT_PORTAL_FRAME_DURATION = 0.1f;
    public static final Vector2 EXIT_PORTAL_DEFAULT_LOCATION = new Vector2(200, 200);
    public static final int INITIAL_LIVES = 3;
    public static final Vector2 DEFAULT_APPEAR_LOCATION = new Vector2(100, 100);
    public static final float HUD_VIEWPORT_SIZE = 480;
    public static final float HUD_MARGIN = 20;
    public static final String HUD_BULLET_LABEL = "Bullet: ";
    public static final String HUD_SCORE_LABEL = "Score: ";
    public static final int ENEMY_KILL_SCORE = 100;
    public static final int POWERUP_SCORE = 50;
    public static final float EXIT_PORTAL_RADIUS = 28;
    public static final String FONT_FILE = "font/header.fnt";
    public static final int BURST_COUNT =500;
    public static final float LEVEL_END_DURATION = 3;
    public static final String WINNING_MESSAGE = "You are the Winner!";
    public static final String GAME_OVER_MESSAGE = "Game Over!";
    public static final String[] LEVELS = {"levels/Level1.dt", "levels/Level2.dt","levels/Level3.dt"};
    public static final float ONSCREEN_CONTROLS_VIEWPORT_SIZE = 200;
    public static final String MOVE_LEFT_BUTTON = "button-move-left";
    public static final String MOVE_RIGHT_BUTTON = "button-move-right";
    public static final String SHOOT_BUTTON = "button-shoot";
    public static final String JUMP_BUTTON = "button-jump";
    public static final String PAUSE = "Pause";
    public static final Vector2 BUTTON_CENTER = new Vector2(15, 15);
    public static final float BUTTON_RADIUS = 32;
}
